# Generated by Django 3.0.8 on 2020-08-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='fb_profile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='gmail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='insta_profile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='quote',
            field=models.CharField(default='', max_length=200),
        ),
    ]
